#!/usr/bin/with-contenv bash

# Wait for ADB to become available
timeout 60 bash -c \
    "until echo > /dev/tcp/localhost/5037 ; do sleep 0.5; done" \
        > /dev/null 2>&1;

if [ -z "$DEVICES" ]
then
    echo "Devices list is empty"
else
    IFS=';' read -ra ADDR <<< "$DEVICES"
    for i in "${ADDR[@]}"; do
        adb connect $i
    done
fi

# Sleep until next loop
exec sleep $TIMEOUT
